# -- Custom image --
FROM jupyter/base-notebook

# Install base dependencies
RUN mamba install --yes \
      duckdb \
      geopandas \
      jupytext \
      matplotlib \
      pandas \
      seaborn
