# Generated by Django 5.1.3 on 2024-12-06 14:53

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qcd_consent", "0001_initial"),
        (
            "qcd_core",
            "0003_alter_deliverypoint_managers_alter_entity_proxy_for_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="consent",
            managers=[
                ("active_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="consent",
            name="delivery_point",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consents",
                to="qcd_core.deliverypoint",
            ),
        ),
    ]
