# Generated by Django 5.1.4 on 2024-12-20 14:13

import apps.consent.utils
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qcd_consent", "0002_alter_consent_managers_alter_consent_delivery_point"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="consent",
            managers=[],
        ),
        migrations.AlterField(
            model_name="consent",
            name="end",
            field=models.DateTimeField(
                default=apps.consent.utils.consent_end_date, verbose_name="end date"
            ),
        ),
        migrations.AlterField(
            model_name="consent",
            name="start",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="start date"
            ),
        ),
    ]
