# Generated by Django 5.1.5 on 2025-01-26 16:01

import apps.consent.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qcd_consent", "0003_alter_consent_managers_alter_consent_end_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consent",
            name="allows_daily_index_readings",
            field=models.BooleanField(
                default=False,
                verbose_name="allow history of daily index readings in kWh",
            ),
        ),
        migrations.AddField(
            model_name="consent",
            name="allows_load_curve",
            field=models.BooleanField(
                default=False,
                verbose_name="allows history of load curve, at steps returned by Enedis",
            ),
        ),
        migrations.AddField(
            model_name="consent",
            name="allows_max_daily_power",
            field=models.BooleanField(
                default=False,
                verbose_name="allows historical maximum daily power in kVa or kWh ",
            ),
        ),
        migrations.AddField(
            model_name="consent",
            name="allows_measurements",
            field=models.BooleanField(
                default=False, verbose_name="allows historical measurements in kWh"
            ),
        ),
        migrations.AddField(
            model_name="consent",
            name="allows_technical_contractual_data",
            field=models.BooleanField(
                default=False,
                verbose_name="allows the technical and contractual data available",
            ),
        ),
        migrations.AddField(
            model_name="consent",
            name="company",
            field=models.JSONField(
                blank=True,
                default=None,
                null=True,
                validators=[apps.consent.validators.validate_company_schema],
                verbose_name="company informations",
            ),
        ),
        migrations.AddField(
            model_name="consent",
            name="company_representative",
            field=models.JSONField(
                blank=True,
                default=None,
                null=True,
                validators=[apps.consent.validators.validate_representative_schema],
                verbose_name="company representative informations",
            ),
        ),
        migrations.AddField(
            model_name="consent",
            name="control_authority",
            field=models.JSONField(
                blank=True,
                default=None,
                null=True,
                validators=[apps.consent.validators.validate_control_authority_schema],
                verbose_name="control authority informations",
            ),
        ),
        migrations.AddField(
            model_name="consent",
            name="is_authoritative_signatory",
            field=models.BooleanField(
                default=False,
                verbose_name="the signatory has the authority to sign this consent",
            ),
        ),
        migrations.AddField(
            model_name="consent",
            name="signature_location",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="signature location"
            ),
        ),
        migrations.AddField(
            model_name="consent",
            name="signed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="signature date"
            ),
        ),
    ]
