# Generated by Django 5.1.7 on 2025-03-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qcd_consent", "0004_consent_contractual_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="consent",
            name="contract_holder_email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                verbose_name="contract holder email address",
            ),
        ),
        migrations.AddField(
            model_name="consent",
            name="contract_holder_name",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="contract holder name",
            ),
        ),
        migrations.AddField(
            model_name="consent",
            name="contract_holder_phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="contract holder phone number",
            ),
        ),
    ]
