# Generated by Django 5.1.7 on 2025-03-11 08:34

import apps.consent.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qcd_consent", "0005_consent_contract_holder_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consent",
            name="contract_holder_email",
        ),
        migrations.RemoveField(
            model_name="consent",
            name="contract_holder_name",
        ),
        migrations.RemoveField(
            model_name="consent",
            name="contract_holder_phone",
        ),
        migrations.AddField(
            model_name="consent",
            name="contract_holder",
            field=models.JSONField(
                blank=True,
                default=None,
                null=True,
                validators=[apps.consent.validators.validate_contract_holder_schema],
                verbose_name="contract holder informations",
            ),
        ),
    ]
