# Generated by Django 5.1.7 on 2025-03-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qcd_consent", "0006_remove_consent_contract_holder_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consent",
            name="id_station_itinerance",
            field=models.CharField(
                blank=True, max_length=35, verbose_name="id station itinerance"
            ),
        ),
        migrations.AddField(
            model_name="consent",
            name="provider_assigned_id",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="provider assigned id"
            ),
        ),
        migrations.AddField(
            model_name="consent",
            name="station_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="station name"
            ),
        ),
    ]
