# Generated by Django 5.1.7 on 2025-03-31 09:42

import apps.consent.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qcd_consent", "0007_consent_id_station_itinerance_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="consent",
            options={
                "ordering": [
                    "delivery_point__station_name",
                    "provider_assigned_id",
                    "start",
                ]
            },
        ),
        migrations.AlterField(
            model_name="consent",
            name="start",
            field=models.DateTimeField(
                default=apps.consent.utils.consent_start_date, verbose_name="start date"
            ),
        ),
    ]
