# Generated by Django 5.1.8 on 2025-04-07 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qcd_consent", "0008_alter_consent_options_alter_consent_start"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="consent",
            options={"ordering": ["provider_assigned_id", "start"]},
        ),
        migrations.RemoveField(
            model_name="consent",
            name="id_station_itinerance",
        ),
        migrations.RemoveField(
            model_name="consent",
            name="station_name",
        ),
    ]
