# Generated by Django 5.1.8 on 2025-04-03 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qcd_consent", "0008_alter_consent_options_alter_consent_start"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="consent",
            options={"ordering": ["provider_assigned_id", "start"]},
        ),
    ]
