# Generated by Django 5.1.5 on 2025-02-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qcd_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboarduser",
            name="siret",
            field=models.CharField(
                blank=True, default="", max_length=14, verbose_name="SIRET"
            ),
        ),
    ]
