# Generated by Django 5.1.6 on 2025-02-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qcd_auth", "0002_dashboarduser_siret"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboarduser",
            name="is_validated",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this user has been validated by the QualiCharge team.",
                verbose_name="is validated",
            ),
        ),
    ]
