#!/usr/bin/env bash

set -eo pipefail

# Create .htpasswd file for ngnix
echo "${DATA7_HTPASSWD}" > .htpasswd

# Run data7 server in the background
data7 run --no-reload --workers 1 &

# Run nginx
#
# Nota bene: the bin/run script is generated by the nginx buildpack
bin/run &

# If the current script is killed, also terminate all child background jobs
trap "pkill SIGTERM -P $$" SIGTERM EXIT

# wait for a single child to finish,
wait -n

# then kill all the other tasks
pkill -P $$
