"""add admin geo boundaries

Revision ID: 7b8c33d8399d
Revises: b5ef0fba88a7
Create Date: 2024-07-29 08:57:49.939396

"""

from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "7b8c33d8399d"
down_revision: Union[str, None] = "b5ef0fba88a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "epci",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "geometry",
            geoalchemy2.types.Geometry(
                srid=4326, from_text="ST_GeomFromEWKT", name="geometry", nullable=False
            ),
            nullable=False,
        ),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.CheckConstraint("created_at <= updated_at", name="pre-creation-update"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_epci_code"), "epci", ["code"], unique=True)
    op.create_table(
        "region",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "geometry",
            geoalchemy2.types.Geometry(
                srid=4326, from_text="ST_GeomFromEWKT", name="geometry", nullable=False
            ),
            nullable=False,
        ),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.CheckConstraint("created_at <= updated_at", name="pre-creation-update"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_region_code"), "region", ["code"], unique=True)
    op.create_table(
        "department",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "geometry",
            geoalchemy2.types.Geometry(
                srid=4326, from_text="ST_GeomFromEWKT", name="geometry", nullable=False
            ),
            nullable=False,
        ),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("region_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint("created_at <= updated_at", name="pre-creation-update"),
        sa.ForeignKeyConstraint(
            ["region_id"],
            ["region.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_department_code"), "department", ["code"], unique=True)
    op.create_table(
        "city",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "geometry",
            geoalchemy2.types.Geometry(
                srid=4326, from_text="ST_GeomFromEWKT", name="geometry", nullable=False
            ),
            nullable=False,
        ),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("department_id", sa.Uuid(), nullable=True),
        sa.Column("epci_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint("created_at <= updated_at", name="pre-creation-update"),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["department.id"],
        ),
        sa.ForeignKeyConstraint(
            ["epci_id"],
            ["epci.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_city_code"), "city", ["code"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_city_code"), table_name="city")
    op.drop_index("idx_city_geometry", table_name="city", postgresql_using="gist")
    op.drop_table("city")
    op.drop_index(op.f("ix_department_code"), table_name="department")
    op.drop_index(
        "idx_department_geometry", table_name="department", postgresql_using="gist"
    )
    op.drop_table("department")
    op.drop_index(op.f("ix_region_code"), table_name="region")
    op.drop_index("idx_region_geometry", table_name="region", postgresql_using="gist")
    op.drop_table("region")
    op.drop_index(op.f("ix_epci_code"), table_name="epci")
    op.drop_index("idx_epci_geometry", table_name="epci", postgresql_using="gist")
    op.drop_table("epci")
    # ### end Alembic commands ###
