"""admin_level_add_population_area

Revision ID: b10e85cde5d0
Revises: d198170d222f
Create Date: 2024-09-05 15:11:38.628739

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "b10e85cde5d0"
down_revision: Union[str, None] = "d198170d222f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "city",
        sa.Column("population", sa.Integer(), nullable=True),
    )
    op.add_column(
        "city", sa.Column("area", sa.Float(), nullable=True)
    )
    op.add_column(
        "department",
        sa.Column("population", sa.Integer(), nullable=True),
    )
    op.add_column(
        "department",
        sa.Column("area", sa.Float(), nullable=True),
    )
    op.add_column(
        "epci",
        sa.Column("population", sa.Integer(), nullable=True),
    )
    op.add_column(
        "epci", sa.Column("area", sa.Float(), nullable=True)
    )
    op.add_column(
        "region",
        sa.Column("population", sa.Integer(), nullable=True),
    )
    op.add_column(
        "region", sa.Column("area", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("region", "area")
    op.drop_column("region", "population")
    op.drop_column("epci", "area")
    op.drop_column("epci", "population")
    op.drop_column("department", "area")
    op.drop_column("department", "population")
    op.drop_column("city", "area")
    op.drop_column("city", "population")
    # ### end Alembic commands ###
