"""handle stations fk

Revision ID: c09664a85912
Revises: 6e610f62bcc6
Create Date: 2024-11-04 13:54:10.737576

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c09664a85912"
down_revision: Union[str, None] = "6e610f62bcc6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "station_operational_unit_id_fkey", "station", type_="foreignkey"
    )
    op.drop_constraint("station_enseigne_id_fkey", "station", type_="foreignkey")
    op.drop_constraint("station_amenageur_id_fkey", "station", type_="foreignkey")
    op.drop_constraint("station_localisation_id_fkey", "station", type_="foreignkey")
    op.drop_constraint("station_operateur_id_fkey", "station", type_="foreignkey")
    op.create_foreign_key(
        "station_operateur_id_fkey",
        "station",
        "operateur",
        ["operateur_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "station_amenageur_id_fkey",
        "station",
        "amenageur",
        ["amenageur_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "station_operational_unit_id_fkey",
        "station",
        "operationalunit",
        ["operational_unit_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "station_enseigne_id_fkey",
        "station",
        "enseigne",
        ["enseigne_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "station_localisation_id_fkey",
        "station",
        "localisation",
        ["localisation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "station_operational_unit_id_fkey", "station", type_="foreignkey"
    )
    op.drop_constraint("station_enseigne_id_fkey", "station", type_="foreignkey")
    op.drop_constraint("station_amenageur_id_fkey", "station", type_="foreignkey")
    op.drop_constraint("station_localisation_id_fkey", "station", type_="foreignkey")
    op.drop_constraint("station_operateur_id_fkey", "station", type_="foreignkey")
    op.create_foreign_key(
        "station_operateur_id_fkey", "station", "operateur", ["operateur_id"], ["id"]
    )
    op.create_foreign_key(
        "station_localisation_id_fkey",
        "station",
        "localisation",
        ["localisation_id"],
        ["id"],
    )
    op.create_foreign_key(
        "station_amenageur_id_fkey", "station", "amenageur", ["amenageur_id"], ["id"]
    )
    op.create_foreign_key(
        "station_enseigne_id_fkey", "station", "enseigne", ["enseigne_id"], ["id"]
    )
    op.create_foreign_key(
        "station_operational_unit_id_fkey",
        "station",
        "operationalunit",
        ["operational_unit_id"],
        ["id"],
    )
    # ### end Alembic commands ###
