"""add tariff schema.

Revision ID: c587b03fe0b4
Revises: 61de84df9030
Create Date: 2026-05-04 12:21:16.606243

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from postgresql_audit.base import versioning_manager
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c587b03fe0b4"
down_revision: Union[str, None] = "61de84df9030"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def get_tables(connection):
    """Get SQLAlchemy tables."""
    metadata = sa.MetaData()
    metadata.reflect(bind=connection, only=("tariff", "pointdechargetariff"))
    return metadata.tables


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tariff",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("updated_by_id", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("original_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("original_last_updated", sa.DateTime(), nullable=False),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("start", sa.DateTime(), nullable=False),
        sa.Column("end", sa.DateTime(), nullable=True),
        sa.CheckConstraint("created_at <= updated_at", name="pre-creation-update"),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "original_id",
            "original_last_updated",
            name="tariff_original_id_original_last_updated_key",
        ),
    )
    op.create_index(op.f("ix_tariff_end"), "tariff", ["end"], unique=False)
    op.create_index(
        op.f("ix_tariff_original_id"), "tariff", ["original_id"], unique=False
    )
    op.create_index(
        op.f("ix_tariff_original_last_updated"),
        "tariff",
        ["original_last_updated"],
        unique=False,
    )
    op.create_index(op.f("ix_tariff_start"), "tariff", ["start"], unique=False)
    op.create_table(
        "pointdechargetariff",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("updated_by_id", sa.Uuid(), nullable=True),
        sa.Column("point_de_charge_id", sa.Uuid(), nullable=False),
        sa.Column("tariff_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("created_at <= updated_at", name="pre-creation-update"),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["point_de_charge_id"],
            ["_pointdecharge.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tariff_id"],
            ["tariff.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("point_de_charge_id", "tariff_id"),
    )

    connection = op.get_bind()
    tables = get_tables(connection)
    excluded = ["created_at", "updated_at"]
    versioned_tables = [
        tables["tariff"],
        tables["pointdechargetariff"],
    ]
    for table in versioned_tables:
        op.execute(
            versioning_manager.build_audit_table_query(
                table=table,
                exclude_columns=excluded,
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    tables = get_tables(connection)
    for table in (tables["tariff"], tables["pointdechargetariff"]):
        for trigger in (
            "audit_trigger_insert",
            "audit_trigger_update",
            "audit_trigger_delete",
        ):
            op.execute(f'DROP TRIGGER "{trigger}" ON "{table.name}" CASCADE')

    op.drop_table("pointdechargetariff")
    op.drop_index(op.f("ix_tariff_start"), table_name="tariff")
    op.drop_index(op.f("ix_tariff_original_last_updated"), table_name="tariff")
    op.drop_index(op.f("ix_tariff_original_id"), table_name="tariff")
    op.drop_index(op.f("ix_tariff_end"), table_name="tariff")
    op.drop_table("tariff")
    # ### end Alembic commands ###
