"""localisation_code_insee_commune_is_required

Revision ID: d198170d222f
Revises: d1e96368f232
Create Date: 2024-09-04 15:20:57.493230

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d198170d222f"
down_revision: Union[str, None] = "d1e96368f232"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "localisation", "code_insee_commune", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "localisation", "code_insee_commune", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###
