"""id_pdc_itinerance should be unique

Revision ID: d1e96368f232
Revises: f5416bc7dd5f
Create Date: 2024-07-31 15:25:26.997834

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d1e96368f232"
down_revision: Union[str, None] = "f5416bc7dd5f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_pointdecharge_id_pdc_itinerance", table_name="pointdecharge")
    op.create_index(
        op.f("ix_pointdecharge_id_pdc_itinerance"),
        "pointdecharge",
        ["id_pdc_itinerance"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_pointdecharge_id_pdc_itinerance"), table_name="pointdecharge"
    )
    op.create_index(
        "ix_pointdecharge_id_pdc_itinerance",
        "pointdecharge",
        ["id_pdc_itinerance"],
        unique=False,
    )
    # ### end Alembic commands ###
