"""remove location unique together constraint

Revision ID: da896549e09c
Revises: b7d33b01adac
Create Date: 2024-04-29 17:20:56.671209

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "da896549e09c"
down_revision: Union[str, None] = "b7d33b01adac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "localisation_adresse_station_coordonneesXY_key", "localisation", type_="unique"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "localisation_adresse_station_coordonneesXY_key",
        "localisation",
        ["adresse_station", "coordonneesXY"],
    )
    # ### end Alembic commands ###
