"""add operational unit data

Revision ID: fda96abb970d
Revises: 9d22385a3ae8
Create Date: 2024-05-15 16:08:19.687606

"""

from datetime import datetime, timezone
from typing import Sequence, Union
from uuid import uuid4

from sqlalchemy import MetaData

from alembic import op

from qualicharge.fixtures.operational_units import data as operational_units


# revision identifiers, used by Alembic.
revision: str = "fda96abb970d"
down_revision: Union[str, None] = "9d22385a3ae8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    data_upgrades()


def downgrade():
    data_downgrades()


def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    # Reset table before inserting data
    data_downgrades()

    # Get OperationalUnit table
    metadata = MetaData()
    metadata.reflect(bind=op.get_bind())
    ou_table = metadata.tables["operationalunit"]

    # Bulk insert
    now = datetime.now(timezone.utc)
    selected_operational_units = [
        "FR073",
        "FR0NX",
        "FR147",
        "FR281",
        "FR2AC",
        "FR3R3",
        "FR55C",
        "FR594",
        "FR5GS",
        "FR730",
        "FR777",
        "FR911",
        "FRA02",
        "FRA03",
        "FRA04",
        "FRA05",
        "FRA07",
        "FRA15",
        "FRA16",
        "FRA21",
        "FRA22",
        "FRA30",
        "FRA31",
        "FRA51",
        "FRA87",
        "FRA88",
        "FRABA",
        "FRACA",
        "FRADP",
        "FRAIR",
        "FRALL",
        "FRALS",
        "FRANG",
        "FRAPR",
        "FRAPS",
        "FRARE",
        "FRATL",
        "FRAUT",
        "FRAVE",
        "FRBAT",
        "FRBBJ",
        "FRBCC",
        "FRBE1",
        "FRBE2",
        "FRBEC",
        "FRBHM",
        "FRBMP",
        "FRBPF",
        "FRBR1",
        "FRBRS",
        "FRBS1",
        "FRBSC",
        "FRBSP",
        "FRC01",
        "FRC2A",
        "FRC2N",
        "FRC2P",
        "FRC4F",
        "FRCAR",
        "FRCG0",
        "FRCHA",
        "FRCHK",
        "FRCIT",
        "FRCM1",
        "FRCNT",
        "FRCOF",
        "FRCPI",
        "FRCTS",
        "FRDMB",
        "FRDNP",
        "FRDOU",
        "FRDRE",
        "FRDRV",
        "FRDS6",
        "FRDWD",
        "FRE04",
        "FRE05",
        "FRE08",
        "FRE10",
        "FRE11",
        "FRE12",
        "FRE27",
        "FRE32",
        "FRE44",
        "FRE45",
        "FRE47",
        "FRE59",
        "FREAB",
        "FREBN",
        "FRECH",
        "FRECN",
        "FRECP",
        "FREDI",
        "FREES",
        "FREFC",
        "FREFL",
        "FREGR",
        "FRELC",
        "FRELM",
        "FRELY",
        "FREMI",
        "FRENR",
        "FREOL",
        "FREPA",
        "FREPI",
        "FRESE",
        "FRESL",
        "FREST",
        "FRETI",
        "FREVA",
        "FREVC",
        "FREVE",
        "FREVZ",
        "FREXA",
        "FREZD",
        "FRFAS",
        "FRFLB",
        "FRFR0",
        "FRFR1",
        "FRFR2",
        "FRFR3",
        "FRFRS",
        "FRFUL",
        "FRG02",
        "FRG05",
        "FRG06",
        "FRG10",
        "FRG11",
        "FRG29",
        "FRG38",
        "FRG51",
        "FRG53",
        "FRG58",
        "FRGCE",
        "FRGFX",
        "FRGMB",
        "FRGMO",
        "FRGOB",
        "FRGRN",
        "FRGSP",
        "FRGYM",
        "FRH01",
        "FRH02",
        "FRH03",
        "FRH04",
        "FRH05",
        "FRH06",
        "FRH07",
        "FRH08",
        "FRH09",
        "FRH10",
        "FRH11",
        "FRH13",
        "FRH15",
        "FRH16",
        "FRH17",
        "FRH18",
        "FRH19",
        "FRH20",
        "FRH21",
        "FRHF1",
        "FRHPB",
        "FRHPC",
        "FRIEN",
        "FRIIM",
        "FRIKA",
        "FRIND",
        "FRION",
        "FRIOY",
        "FRIPK",
        "FRISC",
        "FRISE",
        "FRIXL",
        "FRIZF",
        "FRIZM",
        "FRJRC",
        "FRKV2",
        "FRLAF",
        "FRLDL",
        "FRLE1",
        "FRLE2",
        "FRLEK",
        "FRLGC",
        "FRLGE",
        "FRLIB",
        "FRLMC",
        "FRLMS",
        "FRLOD",
        "FRLPA",
        "FRLPI",
        "FRLST",
        "FRLUM",
        "FRM13",
        "FRM29",
        "FRM31",
        "FRM34",
        "FRM38",
        "FRM54",
        "FRM59",
        "FRMAP",
        "FRMAU",
        "FRMBA",
        "FRMBI",
        "FRMBP",
        "FRMBZ",
        "FRMEL",
        "FRMFC",
        "FRMGP",
        "FRMOB",
        "FRMON",
        "FRMW1",
        "FRN54",
        "FRNXS",
        "FROBS",
        "FRONE",
        "FRORV",
        "FROTH",
        "FROZE",
        "FRP01",
        "FRP07",
        "FRPA1",
        "FRPAM",
        "FRPAN",
        "FRPD1",
        "FRPHI",
        "FRPL1",
        "FRPL2",
        "FRPL3",
        "FRPR1",
        "FRPRP",
        "FRPVD",
        "FRPY1",
        "FRQOV",
        "FRQPK",
        "FRQWC",
        "FRQWT",
        "FRRBO",
        "FRREB",
        "FRRIR",
        "FRRM1",
        "FRRMA",
        "FRROC",
        "FRROS",
        "FRRSE",
        "FRS02",
        "FRS08",
        "FRS09",
        "FRS11",
        "FRS12",
        "FRS13",
        "FRS14",
        "FRS16",
        "FRS17",
        "FRS19",
        "FRS21",
        "FRS22",
        "FRS23",
        "FRS24",
        "FRS27",
        "FRS28",
        "FRS30",
        "FRS31",
        "FRS32",
        "FRS33",
        "FRS34",
        "FRS35",
        "FRS36",
        "FRS37",
        "FRS40",
        "FRS41",
        "FRS42",
        "FRS44",
        "FRS46",
        "FRS47",
        "FRS48",
        "FRS49",
        "FRS50",
        "FRS51",
        "FRS52",
        "FRS53",
        "FRS54",
        "FRS55",
        "FRS56",
        "FRS59",
        "FRS60",
        "FRS61",
        "FRS62",
        "FRS63",
        "FRS64",
        "FRS66",
        "FRS68",
        "FRS69",
        "FRS71",
        "FRS72",
        "FRS76",
        "FRS77",
        "FRS80",
        "FRS81",
        "FRS82",
        "FRS84",
        "FRS85",
        "FRS86",
        "FRS87",
        "FRS88",
        "FRS90",
        "FRS91",
        "FRS95",
        "FRSAE",
        "FRSDG",
        "FRSE1",
        "FRSE2",
        "FRSE3",
        "FRSEC",
        "FRSEO",
        "FRSEV",
        "FRSFS",
        "FRSGA",
        "FRSHE",
        "FRSHL",
        "FRSIG",
        "FRSIP",
        "FRSJS",
        "FRSLF",
        "FRSMI",
        "FRSOD",
        "FRSPS",
        "FRSSD",
        "FRSTB",
        "FRSUA",
        "FRSUN",
        "FRSWC",
        "FRSWI",
        "FRSWS",
        "FRSYS",
        "FRT2P",
        "FRTCB",
        "FRTDA",
        "FRTEC",
        "FRTLS",
        "FRTNM",
        "FRTSC",
        "FRTSL",
        "FRUBI",
        "FRURW",
        "FRV05",
        "FRV07",
        "FRV09",
        "FRV12",
        "FRV14",
        "FRV15",
        "FRV16",
        "FRV17",
        "FRV18",
        "FRV19",
        "FRV20",
        "FRV21",
        "FRV51",
        "FRV75",
        "FRVEV",
        "FRVGF",
        "FRVIA",
        "FRVIS",
        "FRVLT",
        "FRW10",
        "FRW11",
        "FRWA1",
        "FRWA2",
        "FRWA3",
        "FRWA4",
        "FRWA5",
        "FRWA6",
        "FRWA7",
        "FRWA8",
        "FRWA9",
        "FRWAT",
        "FRWBC",
        "FRWGO",
        "FRWRN",
        "FRX75",
        "FRY01",
        "FRY02",
        "FRY03",
        "FRY04",
        "FRY05",
        "FRY06",
        "FRY07",
        "FRY08",
        "FRY09",
        "FRY10",
        "FRY11",
        "FRY12",
        "FRY13",
        "FRY14",
        "FRY15",
        "FRY16",
        "FRY17",
        "FRY18",
        "FRY19",
        "FRY20",
        "FRY21",
        "FRY22",
        "FRY23",
        "FRY24",
        "FRY25",
        "FRY26",
        "FRY27",
        "FRY28",
        "FRY29",
        "FRY30",
        "FRY31",
        "FRY32",
        "FRY33",
        "FRY34",
        "FRY35",
        "FRY36",
        "FRY55",
        "FRZAR",
        "FRZBK",
        "FRZHO",
        "FRZHR",
        "FRZIM",
        "FRZKA",
        "FRZMA",
        "FRZP1",
        "FRZPE",
        "FRZSU",
        "FRZTL",
        "FRZUN",
        "FRZWO",
    ]
    op.bulk_insert(
        ou_table,
        [
            {
                "id": uuid4().hex,
                "created_at": now,
                "updated_at": now,
                "type": "CHARGING",
            }
            | ou._asdict()
            for ou in operational_units
            if ou.code in selected_operational_units
        ],
    )

    # Create FK
    op.execute(
        """
        WITH station_ou AS (
                SELECT
                  Station.id as station_id,
                  OperationalUnit.id as operational_unit_id
                FROM
                  Station
                  INNER JOIN OperationalUnit ON
                    SUBSTRING(Station.id_station_itinerance, 1, 5) = OperationalUnit.code
            )
            UPDATE Station
            SET operational_unit_id = station_ou.operational_unit_id
            FROM station_ou
            WHERE Station.id = station_ou.station_id
        """
    )


def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    # Reset FK
    op.execute("UPDATE Station SET operational_unit_id = NULL")

    # Delete records
    op.execute("DELETE FROM OperationalUnit")
