#!/usr/bin/env bash

# We may expect that the following environment variables are set:
#
#   - PORT: the server port
#   - QUALICHARGE_DEBUG: activate the debug mode (for development) [*]
#
# [*] optional

set -euo pipefail

declare -i debug=${QUALICHARGE_DEBUG:-0}
declare -i workers=${QUALICHARGE_UVICORN_WORKERS:-1}
declare -a extra_opts

if [ ${debug} == 1 ]; then
  extra_opts=(
    "--reload" \
    "--log-config logging-config.dev.yaml"
  )
  echo "⚗️ DEBUG mode activated. We hope your are not running in production. 🤞"
else
  extra_opts=(
    "--workers ${workers}" \
    "--log-config logging-config.prod.yaml" \
    "--no-access-log"
  )
fi

# Run uvicorn in the background so that we can also run nginx
# shellcheck disable=SC2068
uvicorn \
  qualicharge.api:app \
  --proxy-headers \
  --host 0.0.0.0 \
  --port "${QUALICHARGE_API_PORT}" \
  ${extra_opts[@]} &

# Run nginx
#
# Nota bene: the bin/run script is generated by the nginx buildpack
bin/run &

# If the current script is killed, also terminate all child background jobs
trap "pkill SIGTERM -P $$" SIGTERM EXIT

# wait for a single child to finish,
wait -n

# then kill all the other tasks
pkill -P $$
