# Generated by Django 5.1.8 on 2025-04-17 09:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("qcd_core", "0010_station"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Renewable",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="updated at"
                    ),
                ),
                ("meter_reading", models.FloatField(verbose_name="meter reading")),
                ("collected_at", models.DateTimeField(verbose_name="collection date")),
                ("signed_at", models.DateTimeField(verbose_name="signature date")),
                (
                    "signature_location",
                    models.CharField(max_length=255, verbose_name="signature location"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "delivery_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="renewables",
                        to="qcd_core.deliverypoint",
                    ),
                ),
            ],
            options={
                "ordering": ["delivery_point__provider_assigned_id", "collected_at"],
            },
        ),
    ]
