# Generated by Django 5.1.8 on 2025-04-28 15:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qcd_renewable", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="renewable",
            name="has_confirmed_information_accuracy",
            field=models.BooleanField(
                default=False, verbose_name="has confirmed information accuracy"
            ),
        ),
        migrations.AlterField(
            model_name="renewable",
            name="meter_reading",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(
                        0.0, message="The value must be positive"
                    )
                ],
                verbose_name="meter reading",
            ),
        ),
    ]
