# Generated by Django 5.1.8 on 2025-04-15 14:06

import apps.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("qcd_core", "0001_initial"),
        ("qcd_core", "0002_alter_deliverypoint_entity"),
        (
            "qcd_core",
            "0003_alter_deliverypoint_managers_alter_entity_proxy_for_and_more",
        ),
        ("qcd_core", "0004_entity_company_informations"),
        ("qcd_core", "0005_entity_contract_holder_email_and_more"),
        ("qcd_core", "0006_deliverypoint_id_station_itinerance_and_more"),
        ("qcd_core", "0007_entity_synced_at"),
        ("qcd_core", "0008_alter_deliverypoint_provider_assigned_id_and_more"),
        ("qcd_core", "0009_remove_deliverypoint_unique_provider_station_and_more"),
        ("qcd_core", "0010_station"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="updated at"
                    ),
                ),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        populate_from="name",
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=64, unique=True, verbose_name="name"),
                ),
                (
                    "proxy_for",
                    models.ManyToManyField(
                        blank=True,
                        related_name="proxies",
                        to="qcd_core.entity",
                        verbose_name="proxy for",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="entities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="users",
                    ),
                ),
                (
                    "address_1",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="address"
                    ),
                ),
                (
                    "address_2",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="address complement",
                    ),
                ),
                (
                    "address_city",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="city"
                    ),
                ),
                (
                    "address_zip_code",
                    models.CharField(
                        blank=True,
                        max_length=5,
                        null=True,
                        validators=[apps.core.validators.validate_zip_code],
                        verbose_name="zip code",
                    ),
                ),
                (
                    "company_type",
                    models.CharField(
                        choices=[
                            ("ENTERPRISE", "Entreprise"),
                            ("LOCAL_COLLECTIVITY", "Collectivité locale"),
                            ("EPCI", "EPCI"),
                            ("ASSOCIATION", "Association, copropriété, ..."),
                        ],
                        default="ENTERPRISE",
                        max_length=50,
                        verbose_name="type",
                    ),
                ),
                (
                    "legal_form",
                    models.CharField(
                        blank=True,
                        help_text="SA, SARL …",
                        max_length=50,
                        null=True,
                        verbose_name="legal form",
                    ),
                ),
                (
                    "naf",
                    models.CharField(
                        blank=True,
                        max_length=5,
                        null=True,
                        validators=[apps.core.validators.validate_naf_code],
                        verbose_name="NAF code",
                    ),
                ),
                (
                    "siret",
                    models.CharField(
                        blank=True,
                        max_length=14,
                        null=True,
                        validators=[apps.core.validators.validate_siret],
                        verbose_name="SIRET",
                    ),
                ),
                (
                    "trade_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="trade name"
                    ),
                ),
                (
                    "contract_holder_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="contract holder email address",
                    ),
                ),
                (
                    "contract_holder_name",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="contract holder name",
                    ),
                ),
                (
                    "contract_holder_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="contract holder phone number",
                    ),
                ),
                (
                    "synced_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Last synchronization with the API occurred at",
                    ),
                ),
            ],
            options={
                "verbose_name": "entity",
                "verbose_name_plural": "entities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryPoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="updated at"
                    ),
                ),
                (
                    "provider_assigned_id",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="provider assigned id"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_points",
                        to="qcd_core.entity",
                        verbose_name="entity",
                    ),
                ),
            ],
            options={
                "verbose_name": "delivery point",
                "verbose_name_plural": "delivery points",
                "ordering": ["provider_assigned_id"],
            },
            managers=[
                ("active_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="updated at"
                    ),
                ),
                (
                    "id_station_itinerance",
                    models.CharField(
                        blank=True,
                        max_length=35,
                        unique=True,
                        verbose_name="id station itinerance",
                    ),
                ),
                (
                    "station_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="station name"
                    ),
                ),
                (
                    "delivery_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stations",
                        to="qcd_core.deliverypoint",
                        verbose_name="delivery point",
                    ),
                ),
            ],
            options={
                "verbose_name": "station",
                "verbose_name_plural": "stations",
                "ordering": ["station_name", "id_station_itinerance"],
            },
        ),
    ]
