# Generated by Django 5.1.3 on 2024-11-29 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qcd_core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverypoint",
            name="entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_points",
                to="qcd_core.entity",
                verbose_name="entity",
            ),
        ),
    ]
