# Generated by Django 5.1.3 on 2024-12-06 14:53

import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qcd_core", "0002_alter_deliverypoint_entity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="deliverypoint",
            managers=[
                ("active_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="entity",
            name="proxy_for",
            field=models.ManyToManyField(
                blank=True,
                related_name="proxies",
                to="qcd_core.entity",
                verbose_name="proxy for",
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="users",
            field=models.ManyToManyField(
                related_name="entities",
                to=settings.AUTH_USER_MODEL,
                verbose_name="users",
            ),
        ),
    ]
