# Generated by Django 5.1.5 on 2025-01-30 09:02

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "qcd_core",
            "0003_alter_deliverypoint_managers_alter_entity_proxy_for_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="address_1",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="address"
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="address_2",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="address complement"
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="address_city",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="city"
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="address_zip_code",
            field=models.CharField(
                blank=True,
                max_length=5,
                null=True,
                validators=[apps.core.validators.validate_zip_code],
                verbose_name="zip code",
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="company_type",
            field=models.CharField(
                choices=[
                    ("ENTERPRISE", "Entreprise"),
                    ("LOCAL_COLLECTIVITY", "Collectivité locale"),
                    ("EPCI", "EPCI"),
                    ("ASSOCIATION", "Association, copropriété, ..."),
                ],
                default="ENTERPRISE",
                max_length=50,
                verbose_name="type",
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="legal_form",
            field=models.CharField(
                blank=True,
                help_text="SA, SARL …",
                max_length=50,
                null=True,
                verbose_name="legal form",
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="naf",
            field=models.CharField(
                blank=True,
                max_length=5,
                null=True,
                validators=[apps.core.validators.validate_naf_code],
                verbose_name="NAF code",
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="siret",
            field=models.CharField(
                blank=True,
                max_length=14,
                null=True,
                validators=[apps.core.validators.validate_siret],
                verbose_name="SIRET",
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="trade_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="trade name"
            ),
        ),
    ]
