# Generated by Django 5.1.7 on 2025-03-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qcd_core", "0005_entity_contract_holder_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverypoint",
            name="id_station_itinerance",
            field=models.CharField(
                blank=True, max_length=35, verbose_name="id station itinerance"
            ),
        ),
        migrations.AddField(
            model_name="deliverypoint",
            name="station_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="station name"
            ),
        ),
        migrations.AlterField(
            model_name="deliverypoint",
            name="provider_assigned_id",
            field=models.CharField(
                max_length=64, unique=True, verbose_name="provider assigned id"
            ),
        ),
    ]
