# Generated by Django 5.1.7 on 2025-03-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qcd_core", "0006_deliverypoint_id_station_itinerance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="synced_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Last synchronization with the API occurred at",
            ),
        ),
    ]
