# Generated by Django 5.1.7 on 2025-03-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qcd_core", "0007_entity_synced_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverypoint",
            name="provider_assigned_id",
            field=models.CharField(max_length=64, verbose_name="provider assigned id"),
        ),
        migrations.AddConstraint(
            model_name="deliverypoint",
            constraint=models.UniqueConstraint(
                fields=("provider_assigned_id", "id_station_itinerance"),
                name="unique_provider_station",
            ),
        ),
    ]
