# Generated by Django 5.1.8 on 2025-04-03 13:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qcd_core", "0008_alter_deliverypoint_provider_assigned_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="updated at"
                    ),
                ),
                (
                    "id_station_itinerance",
                    models.CharField(
                        blank=True,
                        max_length=35,
                        unique=True,
                        verbose_name="id station itinerance",
                    ),
                ),
                (
                    "station_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="station name"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveConstraint(
            model_name="deliverypoint",
            name="unique_provider_station",
        ),
        migrations.RemoveField(
            model_name="deliverypoint",
            name="id_station_itinerance",
        ),
        migrations.RemoveField(
            model_name="deliverypoint",
            name="station_name",
        ),
        migrations.AlterField(
            model_name="deliverypoint",
            name="provider_assigned_id",
            field=models.CharField(
                max_length=64, unique=True, verbose_name="provider assigned id"
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="delivery_point",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stations",
                to="qcd_core.deliverypoint",
                verbose_name="delivery point",
            ),
        ),
    ]
