# Generated by Django 5.1.8 on 2025-04-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qcd_core", "0008_alter_deliverypoint_provider_assigned_id_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="deliverypoint",
            name="unique_provider_station",
        ),
        migrations.RemoveField(
            model_name="deliverypoint",
            name="id_station_itinerance",
        ),
        migrations.RemoveField(
            model_name="deliverypoint",
            name="station_name",
        ),
        migrations.AlterField(
            model_name="deliverypoint",
            name="provider_assigned_id",
            field=models.CharField(
                max_length=64, unique=True, verbose_name="provider assigned id"
            ),
        ),
    ]
