# Generated by Django 5.1.8 on 2025-04-07 13:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qcd_core", "0009_remove_deliverypoint_unique_provider_station_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="updated at"
                    ),
                ),
                (
                    "id_station_itinerance",
                    models.CharField(
                        blank=True,
                        max_length=35,
                        unique=True,
                        verbose_name="id station itinerance",
                    ),
                ),
                (
                    "station_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="station name"
                    ),
                ),
                (
                    "delivery_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stations",
                        to="qcd_core.deliverypoint",
                        verbose_name="delivery point",
                    ),
                ),
            ],
            options={
                "verbose_name": "station",
                "verbose_name_plural": "stations",
                "ordering": ["station_name", "id_station_itinerance"],
            },
        ),
    ]
