# Generated by Django 5.1.8 on 2025-04-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qcd_core", "0001_squashed_0010_station"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="deliverypoint",
            managers=[],
        ),
        migrations.AddField(
            model_name="deliverypoint",
            name="has_renewable",
            field=models.BooleanField(default=False, verbose_name="has renewable"),
        ),
    ]
