# Generated by Django 5.1.8 on 2025-04-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qcd_core", "0010_station"),
    ]

    operations = [
        migrations.AlterField(
            model_name="station",
            name="id_station_itinerance",
            field=models.CharField(
                blank=True, max_length=35, verbose_name="id station itinerance"
            ),
        ),
        migrations.AddConstraint(
            model_name="station",
            constraint=models.UniqueConstraint(
                fields=("id_station_itinerance", "station_name"),
                name="unique_id_station_itinerance_station_name",
            ),
        ),
    ]
