# Generated by Django 5.1.8 on 2025-05-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qcd_core", "0011_alter_deliverypoint_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="can_bypass_renewable_period",
            field=models.BooleanField(
                default=False, verbose_name="can bypass renewable period"
            ),
        ),
    ]
