#!/usr/bin/env bash

set -eo pipefail

# Create .htpasswd file for ngnix
echo "${PREFECT_HTPASSWD_CLIENT}" > .htpasswd
echo "${PREFECT_HTPASSWD_ADMIN}" >> .htpasswd

# Run database migrations
prefect server database upgrade -y

# Run prefect server in the background
prefect server start &

# Run nginx
#
# Nota bene: the bin/run script is generated by the nginx buildpack
bin/run &

# If the current script is killed, also terminate all child background jobs
trap "pkill SIGTERM -P $$" SIGTERM EXIT

# wait for a single child to finish,
wait -n

# then kill all the other tasks
pkill -P $$
