# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Pipenv
        run: pipx install pipenv
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pipenv"
      - name: Install dependencies
        run: |
          cd src/api
          pipenv install -de .

  lint-api:
    needs: build-api
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/api
    steps:
      - uses: actions/checkout@v4
      - name: Install pipenv
        run: pipx install pipenv
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pipenv"
      - name: Lint with Black
        run: pipenv run black qualicharge tests
      - name: Lint with Ruff
        run: pipenv run ruff check qualicharge tests
      - name: Lint with MyPy
        run: pipenv run mypy qualicharge tests

  test-api:
    needs: build-api
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/api
    steps:
      - uses: actions/checkout@v4
      - name: Install pipenv
        run: pipx install pipenv
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pipenv"
      - name: Test with pytest
        run: pipenv run pytest
